### ISSUE TITLE
Nix/NixOS package

### ISSUE THREAD

**Issue by Br1ght0ne** [taylorthurlow/thicket#4]
I made you one. Can also provide installation instructions.

**Comment by taylorthurlow** [comment]
Sweet! Thanks for doing this. I need to get it up on Homebrew too.

Two things:
* I'm considering dropping the `v` prefix from version numbers because it's not how Crystal repos typically operate
* I see you have `ameba` listed as what looks like a dependency? It's not a dependency anymore, and even when it was, it was only a development dependency.

**Comment by Br1ght0ne** [comment]
Sure, I can drop `ameba` and remove dependencies altogether. And if you drop the `v` prefix, please do this for the subsequent versions only, so I can update the package later.

**Comment by taylorthurlow** [comment]
I just checked out the `shard.yml` spec and I guess that the `v` prefix is supposed to be there? The Crystal repo itself doesn't do anything, but I suppose that's not relevant. No worries about that then.
